# Insipired in https://github.com/pre-commit/action/blob/main/.github/workflows/main.yml
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install pre-commit
        shell: bash
      - run: python -m pip freeze --local
        shell: bash
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      # Disabled, can't run on docker, see https://github.com/orgs/community/discussions/25623
      # - name: self test action
      # uses: ./
